<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[2].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\LuckyController:login' => function () {
    return ($this->privates['service_locator.Eodrgak'] ?? $this->load(__DIR__.'/getServiceLocator_EodrgakService.php'));
}, 'App\\Controller\\LuckyController:registerAction' => function () {
    return ($this->privates['service_locator.u0jyp6Y'] ?? $this->load(__DIR__.'/getServiceLocator_U0jyp6YService.php'));
}, 'App\\Controller\\LuckyController::login' => function () {
    return ($this->privates['service_locator.Eodrgak'] ?? $this->load(__DIR__.'/getServiceLocator_EodrgakService.php'));
}, 'App\\Controller\\LuckyController::registerAction' => function () {
    return ($this->privates['service_locator.u0jyp6Y'] ?? $this->load(__DIR__.'/getServiceLocator_U0jyp6YService.php'));
})));
