<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaBQxXZ\srcDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaBQxXZ/srcDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIaBQxXZ.legacy');

    return;
}

if (!\class_exists(srcDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIaBQxXZ\srcDebugProjectContainer::class, srcDebugProjectContainer::class, false);
}

return new \ContainerIaBQxXZ\srcDebugProjectContainer(array(
    'container.build_hash' => 'IaBQxXZ',
    'container.build_id' => 'd33c3568',
    'container.build_time' => 1517302040,
));
