<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF45ASCu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF45ASCu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF45ASCu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF45ASCu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerF45ASCu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'F45ASCu',
    'container.build_id' => 'e9e9cdb2',
    'container.build_time' => 1517299155,
));
