<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDcGVT2p\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDcGVT2p/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDcGVT2p.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDcGVT2p\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDcGVT2p\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DcGVT2p',
    'container.build_id' => '0cc6a32b',
    'container.build_time' => 1517302005,
));
